spring:
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lpshop?&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  servlet:
    session:
      tracking-modes: cookie


file:
  dir: C:/Users/kojinyoung/Desktop/uploadedFiles/
